### ISSUE TITLE
Meta description improvement

### ISSUE THREAD

**Issue by jackalyst** [theQRL/theqrl.org#101]
Related to issue #46 opened in December 2018 "Meta description and style edits" - this is a continuation of that.

It's been brought up in Discord that the current meta description doesn't properly advocate (perform its job) for The QRL homepage. The goal here is to derive a new meta-description that does.

As a bit of background, the current meta-description for theqrl homepage is:

> The Quantum Resistant Ledger (QRL) is a first-of-its-kind, post-quantum value store and decentralized communication layer proactively tackling the threat advanced Quantum Computers pose to cryptocurrencies.

This shows up on google, truncated, as:

> "The Quantum Resistant Ledger (QRL) is a first-of-its-kind, post-quantum value store and decentralized communication layer proactively tackling the threat"

And on bing this is:

> "The Quantum Resistant Ledger (QRL) is a first-of-its-kind, post-quantum value store and decentralized communication layer proactively tackling the threat advanced Quantum …"

[Moz's guide on meta descriptions](https://moz.com/learn/seo/meta-description) says that "The meta description is an HTML attribute that provides a brief summary of a web page. Search engines such as Google often display the meta description—typically up to 160 characters long—in search results where they can **highly influence user click-through rates.**", emphasis being mine. Moz also says "A page's meta description should intelligently (read: in a natural, active, non-spammy way) employ the keywords that page is targeting, but also create a compelling description that a searcher will want to click. It should be directly relevant to the page it describes, and unique from the descriptions for other pages."

Before contributing to the discussion here, it's recommended to refer to Moz's guide to have a overview of our goals.

**Comment by atoma01** [comment]
Thanks for opening this issue. My fist thought was just change "value store" to "store of value". However after some discussion in discord it seem to me the whole store of value theme really dont need to be in the meta description at all, since it could be covered with a small change in the Whitepaper. see https://github.com/theQRL/Whitepaper/issues/5 

So i have come up with another one to reach a broader audience: "The QRL is a cryptocurrency platform, and communication layer proactively tackling the threat quantum computers pose to digital assets"

**Comment by jackalyst** [comment]
Nice suggestion. Really like the addition of "digital assets" as it can go beyond cryptocurrencies and is larger in scope. The only thing is the "proactively tackling" bit, which can imply to some that we're working on it.

"The QRL is a cryptocurrency platform and communication layer secure against the threat quantum computers pose to digital assets", 128 characters

**Comment by atoma01** [comment]
Good point, how about «The QRL is a cryptocurrency platform and communication layer resistant to the threat quantum computers pose to digital assets»

**Comment by jplomas** [comment]
Stale issue closed with site relaunch
