### ISSUE TITLE
New Tagline

### ISSUE THREAD

**Issue by jackalyst** [theQRL/theqrl.org#106]
As per discord user II

Rather than have "Secure digital assets for longevity", a suggestion could be 

"Longterm Store-of-Value, Currency,  Smart Asset & Token Platform
focussing on Security, Usability; keeping Money Quantum Resistant."

**Comment by Clemdom** [comment]
The language is improved here in my opinion. 

I recommend removing the semicolon after "Usability," and replacing it with ", and."

This would make the full revised tagline

"Long-term Store-of-Value, Currency, Smart Asset & Token Platform
focusing on Security, Usability, and keeping Money Quantum Resistant."

**Comment by jackalyst** [comment]
I think this needs to be taken into the wider context of the rest of the hero:

h1. The Quantum Resistant Ledger
h2. Long-term Store-of-Value, Currency, Smart Asset & Token Platform focusing on Security, Usability, and keeping Money Quantum Resistant.
p. Externally audited enterprise-grade blockchain platform secure against an attack from quantum computers.

Might be a bit long, and there's nothing catchy there. Arguably, "Secure digital assets for longevity" wasn't catchy either. 

We could instead replace "Externally audited enterprise-grade blockchain platform secure against an attack from quantum computers." with "Long-term Store-of-Value, Currency, Smart Asset & Token Platform focusing on Security, Usability, and keeping Money Quantum Resistant." and eliminate "Secure digital assets for longevity" entirely, for example:

![Screenshot from 2019-07-14 10-50-27](https://user-images.githubusercontent.com/232510/61186754-2e768c80-a626-11e9-8a7a-f325031c84e7.png)

**Comment by jackalyst** [comment]
To give some historical context, I briefly went back over 2019 and these are the changes that have been made:

2019-01-03
The Quantum Resistant Ledger
The Quantum Resistant Ledger (QRL) is a first-of-its-kind, post-quantum value store and decentralized communication layer that's proactively tackled the threat advanced Quantum Computers pose to cryptocurrencies.

2019-02-22
The Quantum Resistant Ledger
Secure digital assets for an adversarial future

2019-04-07
The Quantum Resistant ledger
Secure digital assets for an adversarial future
Externally audited enterprise grade blockchain secure against quantum computers today, ready for tomorrow.

2019-04-17
The Quantum Resistant Ledger
Secure digital assets for long term security
Externally audited enterprise-grade blockchain platform secure against an attack from quantum computers.

2019-04-26
The Quantum Resistant Ledger
Secure digital assets for longevity
Externally audited enterprise-grade blockchain platform secure against an attack from quantum computers.

**Comment by jplomas** [comment]
Stale issue closed with site relaunch
