### ISSUE TITLE
Better 404

### ISSUE THREAD

**Issue by homps** [theQRL/theqrl.org#13]
If you follow an old link to the new website you get an ugly 404 error. This is very easily found by following the first result on Google from a simple 'What is QRL' search.

Given there will be blogs etc pointing at some of these old URLs, or this may be a landing page for someone trying to find out about QRL, it's not a great introduction and we should make this better.

Example replication from google search below or simply follow:
https://theqrl.org/faqs/01-intro.html

![whatisqrl](https://user-images.githubusercontent.com/37274833/37558466-9d22bcae-2a0c-11e8-8428-5ac46f034c74.jpg)
![404](https://user-images.githubusercontent.com/37274833/37558467-9d4271e8-2a0c-11e8-8790-34608d4bcbd0.jpg)

**Comment by jackalyst** [comment]
Thank you for reporting this issue.
