### ISSUE TITLE
Hamburger menu doesn't work in mobile version

### ISSUE THREAD

**Issue by cooper7777** [theQRL/theqrl.org#135]
Nothing happens onclick

**Comment by 12remember** [comment]
do you still got the problem ?, what phone do you use and which which ios / android version ?

**Comment by jackalyst** [comment]
This may have been when we were tightening our content security policies:
https://github.com/theQRL/theqrl.org/pull/131

**Comment by jplomas** [comment]
Stale issue closed with site relaunch
