### ISSUE TITLE
Some images are not showing

### ISSUE THREAD

**Issue by cooper7777** [theQRL/theqrl.org#136]
![изображение](https://user-images.githubusercontent.com/31483484/67950417-92838780-fbfa-11e9-9e62-af279afc86ae.png)

Checked in several browsers

**Comment by jackalyst** [comment]
Thanks cooper.

This was because of CSP being applied and not being properly accounted for in the frontend. Are you able to check again to see if pull request #131 fixed it on your end?

**Comment by cooper7777** [comment]
It's ok now
