### ISSUE TITLE
Request for the update: 'explorer.small.png'  and 'wallet2.small.png'

### ISSUE THREAD

**Issue by ksangsu95** [theQRL/theqrl.org#32]
The image files used on the showcase of the QRL wallet and the QRL explorer on the main page of the https://theqrl.org are outdated. Hereby, I am requesting the devs to change the png files to recent mainnet snapshots of the wallet and the explorer as soon as possible. 

P.S. Congrats to all members of QRL community regarding the mainnet launch.

**Comment by jackalyst** [comment]
Thank you for the congratulations. Should be fixed in Pull request #33
