### ISSUE TITLE
Meta description grammar and style edits

### ISSUE THREAD

**Issue by jmxdbx** [theQRL/theqrl.org#46]
In the meta description, *first-of-its-kind* and *post-quantum* are compound modifiers and thus require hyphenation, and *future-proof* is perhaps not something any project wants to make explicit claims about (hence Quantum Resistant rather than Quantum Proof).

I propose:

*The Quantum Resistant Ledger (QRL) is a first-of-its-kind, post-quantum value store and decentralized communication layer proactively tackling the threat advanced Quantum Computers pose to cryptocurrencies.*

https://github.com/theQRL/theqrl.org/blob/master/_includes/head.html

**Comment by jplomas** [comment]
Accepted proposal in #47
